name: todo_appdev
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  time: ^2.1.5
  http: ^1.3.0
  path_provider: ^2.1.5
  qr_flutter: ^4.1.0
  qr_code_scanner_plus: ^2.0.10+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.63.0
  flutter_native_splash: ^2.4.6
  flutter_local_notifications: ^19.2.1
  workmanager: ^0.6.0
  shared_preferences: ^2.5.3
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/config/favicon_io/android-chrome-512x512.png"

flutter:
  uses-material-design: true
  assets:
    - lib/config/magenta_cloud_token
    - lib/config/lang.json
    - lib/config/logo_transparent_cropped.png
    - assets/config/logo_transparent.png
    - assets/config/favicon_io/android-chrome-192x192.png
flutter_native_splash:
  color: "#d4e4ed"

  android: true
  ios: true
  web: false

  android_gravity: center
  fullscreen: true

  # For android 12 and higher this is needed
  android_12:
    color: "#d4e4ed"
    image: assets/config/logo_transparent.png

